### ISSUE TITLE
Django 1.8 support/documentation 

### ISSUE THREAD

**Issue by johnnyz** [novafloss/django-docusign#40]
Is there support for 1.8? I saw there was a ticket opened for 1.7 from the fall of 2014. This would be extremely helpful for a specific project I am working on. 

Also it would be nice if the documentation included a basic example of how to get up an running.

For my project I need to have customers sign a contract to use a service. So something a long the lines of creating a document, having the user sign that document, then updating a database table entry that they have completed it, would be extremely helpful. Doesn't have to be exact to my needs, but I'm sure other potential users would benefit from a little hand holding as well. 

Please let me know if more information could be published or is available else where. Thank you for your time.

**Comment by benoitbryon** [comment]
Hi @johnnyz,
There will be support for django-1.8. I'm not sure current version is compatible. Perhaps some changes will be required. Explanations below...

At the moment, i.e. as of django-docusign 0.11:

* in setup.py, `Django<1.7` is required: https://github.com/novafloss/django-docusign/blob/0.11/setup.py#L39 => There is #2 and now #40 (your ticket) to fix it!
* in Tox configuration, only latest version of Django is tested: https://github.com/novafloss/django-docusign/blob/0.11/tox.ini => Created #41 about Tox.
* django-docusign-0.11 was tested against Django 1.6: https://travis-ci.org/novafloss/django-docusign/jobs/54646407#L336

About priority:

* Feel free to create pull-requests on the tickets mentioned above to speed up the process ;)
* else, it depends on how I can make it as part of PeopleDoc (the company I currently work for) global roadmap, where we are working on the upgrade to Django-1.7 this month, and planning an upgrade to 1.8 next month... Perhaps I will be able to address 1.7 and 1.8 support for both at the same time... But I cannot promise.
* in any ways, support for latest Django versions are a priority in the django-docusign's roadmap.

**Comment by benoitbryon** [comment]
Note: I currently have very little feedback from users outside my company... so reviews, feature requests, documentation requests and bug reports are welcome! Let's make this project better for users of Django and Docusign!

**Comment by johnnyz** [comment]
Benoit, I greatly appreciate your enthusiasm and thorough response! People like you are necessary to make great things like this happen! 

I'm unfortunately I am an intermediate Django user and do not foresee myself being able to help with any of these issues, however, there are many similarities between 1.7 and 1.8 which would lead me to believe that you will be able to allow for 1.7 and 1.8 support at the same time, hopefully! 

Thank you again.

**Comment by benoitbryon** [comment]
Some news: just released [django-anysign] (https://pypi.python.org/pypi/django-anysign/) (django-docusign depends on django-anysign) with support of Django 1.7 and 1.8... So django-docusign may be the next one.

**Comment by smcoll** [comment]
i will likely start a branch with Django 1.8 support soon and make a PR for it.  i'll probably start by reviewing https://github.com/DenJohX/django-docusign, which seems to indicate successful Django 1.8 support, but with a problem in the test suite.  Is there anything i should be aware of?

**Comment by zebuline** [comment]
fixed by #61
