### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by smcoll** [novafloss/django-docusign#68]
The most recent release to PyPI was v0.12 on 2015-09-10.  There have been 8 merged PRs since then; could we issue a v0.13 release?

**Comment by zebuline** [comment]
Yes I planned to make a release after the PRs #57 & #67 are merged. It will be a 1.0 release.

**Comment by zebuline** [comment]
1.0 released

**Comment by smcoll** [comment]
Great, thanks.
